import time as t
print("WELCOME TO DAVE'S DISCORD MADNESS!")
name = input("type your name to start: ")
print("( )")
print("(|)")
print(" ^")
print("[stickman] hello " + name + "!")
t.sleep(2)
print("[stickman] this place is discord!")
t.sleep(1)
print("[discord] 1 new message!")
t.sleep(2)
print("[stickman] a new message!")
t.sleep(2)
print("[stickman] lets look at it!")
t.sleep(1)
print("(0)coolman77")
print("   download more ram here: ram.exe")
t.sleep(1)
print("[stickman] lets download more ram!")
t.sleep(1)
print("[computer] ram.exe downloaded!")
t.sleep(1)
print("[computer] opening ram.exe")
t.sleep(1)
print("[computer] ╜!║.N♦σb»Ö♣")
t.sleep(2)
print("[stickman] Oh no!" + name + "! We are stored on the computer!")
t.sleep(2)
print("[stickman] Get to task manager!")
t.sleep(1)
print("AHH├)\,♪┤∞∞∞Z")
input("game over for now")